#!/usr/bin/env python3

import pygame
from ui.main import GameShellUI
from logic.state_manager import StateManager

def main():
    pygame.init()

    state = StateManager()
    ui = GameShellUI(state)

    ui.run()

if __name__ == "__main__":
    main()
